apiVersion: apps/v1
kind: Deployment
metadata:
  name: candle-event-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candle-event-ingestion
  template:
    metadata:
      labels:
        app: candle-event-ingestion
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: candle-event-ingestion
        image: bsamaha/candle-event-ingestion:latest
        env:
        - name: KAFKA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-user-passwords
              key: client-passwords
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: influxdb-auth
              key: admin-token
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-broker-headless.default.svc.cluster.local:9092"
        - name: KAFKA_SASL_USERNAME
          value: "user1"
        - name: KAFKA_SECURITY_PROTOCOL
          value: "SaslPlaintext"
        - name: KAFKA_SASL_MECHANISM
          value: "ScramSha256"
        - name: KAFKA_GROUP_ID
          value: "candle-event-ingestion-consumer"
        - name: KAFKA_TOPIC
          value: "coinbase-candles"
        - name: INFLUXDB_URL
          value: "http://influxdb-influxdb2.default.svc.cluster.local:80"
        - name: INFLUXDB_BUCKET
          value: "crypto"
        - name: INFLUXDB_ORG
          value: "epochtech"
        - name: INFLUXDB_MAX_RETRIES
          value: "3"
        - name: INFLUXDB_BASE_DELAY_MS
          value: "1000"
        - name: CIRCUIT_BREAKER_FAILURE_THRESHOLD
          value: "5"
        - name: CIRCUIT_BREAKER_BREAK_DURATION_SECONDS
          value: "30"
        resources:
          requests:
            cpu: "400m"
            memory: "1024Mi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 5"]